### ISSUE TITLE
Delegated harvesting by using desktop wallet

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-desktop-wallet#954]
I'm running the following testnet node which has activated harvesting:
sym-test-02.opening-line.jp

I want delegated harvesting with the above my node by using desktop wallet.

So I'm trying, but it doesn't seem to work.
Could someone confirm it, please?

Here's steps:
1. Display Harvesting page
![image](https://user-images.githubusercontent.com/28587337/105494268-e4339880-5cfd-11eb-8243-0e138d870e1b.png)

2. Select sym-test-02.opening-line.jp in Node Url list in Deletegated Harvesting panel
![image](https://user-images.githubusercontent.com/28587337/105494351-00373a00-5cfe-11eb-8637-f9639ab92278.png)

3. Confirm Public Keys
![image](https://user-images.githubusercontent.com/28587337/105494398-12b17380-5cfe-11eb-8ec4-318ad2ed4c45.png)

The public keys in Sign transaction(s) are the followings:
- Linked Account Public Key: 238B200FDDF7CF8C6D5ECE282699D6F02CF9196BDF39B366C4166F1601130228
- Linked Vrf Public Key: A946531A163F15CA3642D9C04D84CCA9D5C20B51298B462BEEA2BA1D51615487
- Linked Node Public Key:F57FB70C3F51663D0DDF47303C93ADC8FDD266DC61BBA67B983052D075FD900E

But these are NOT sym-test-02.opening-line.jp's.
Here're the public keys of sym-test-02.opening-line.jp:

```
cat target/addresses.yml
version: 2
networkType: 152
nemesisGenerationHashSeed: 45FBCF2F0EA36EFA7923C9BC923D6503169651F7FA4EFC46A8EAF5AE09057EBD
nodes:
    -
        name: api-node
        friendlyName: sym-test-02.opening-line.jp
        roles: 'Peer,Api'
        main:
            privateKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            publicKey: 1C0F8DB3485DD5BDB8364DAE52CBE53BD7DBD843C2B2A274DBEFE1266CB38014
            address: TCSPOQKWUROIWJ35TSIQZKYDGE6XJJOUGM5P4PY
        transport:
            privateKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            publicKey: F3A445B6F989E9777B134FFD2455169B53E3FEB9E8ECBA6E5B00B5CD36B13165
            address: TDXZJVXL23CTMDOKEU6XA3FEG6Y4MY3VTQCVEKQ
        remote:
            privateKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            publicKey: E3E8CD3313F9B1C2AD9A4764A48631755B781EFCE933DC0C7FC4D84456A62033
            address: TCNBN4J6EMVZCKBLE7CWCOYQ4YR2G43UZFKM7QY
        vrf:
            privateKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            publicKey: 65D91B10CE50CC0903967E5AB2ABA93E4D70C43356CC344133645AB805D2A507
            address: TAHYMN6PDWHOHRU5Z7NR7HNTEQCV5SDJFJCQ5RQ
```

Whose public keys is shown in the list?

Thanks.
